[project]
name = "date-converter"
version = "1.0a1"
description = "A handy python function to parse and convert datetime, int, and string objects"
readme = "README.md"
license = { file = "LICENSE" }
authors = ["Arnaud van Haaster <dont@me.please>"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI APPROVED :: The Unlicense (Unlicense)",
]
dependencies = [
    "dateparser>=?????",
]
requires-python = ">=3.10"